### PR TITLE
fix digitalWriteFast only for AVR and some more changes

### LINKED ISSUE #84: Compiling for Arduino Due
Hi, how can I compile the library for the Arduino Due?
The compiler gives me a lot of errors but no problems with Arduino Uno, find below just a part of them.

`/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:86: note: in expansion of macro 'digitalPinToPortReg'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                                                      ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1507:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, HIGH);
  ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:85:73: error: 'PORTC' was not declared in this scope
 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))
                                                                         ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:120:12: note: in definition of macro '__atomicWrite__'
 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \
            ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:86: note: in expansion of macro 'digitalPinToPortReg'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                                                      ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1507:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, HIGH);
  ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:122:29: error: 'SREG' was not declared in this scope
 uint8_t register saveSreg = SREG;                          \
                             ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:59: note: in expansion of macro '__atomicWrite__'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                           ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1507:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, HIGH);
  ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:123:5: error: 'cli' was not declared in this scope
 cli();                                                     \
     ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:59: note: in expansion of macro '__atomicWrite__'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                           ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1507:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, HIGH);
  ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp: In static member function 'static void DW1000Class::writeBytes(byte, word, byte*, unsigned int)':
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:85:28: error: 'PORTD' was not declared in this scope
 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))
                            ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:120:12: note: in definition of macro '__atomicWrite__'
 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \
            ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:86: note: in expansion of macro 'digitalPinToPortReg'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                                                      ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1563:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, LOW);
  ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:85:64: error: 'PORTB' was not declared in this scope
 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))
                                                                ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:120:12: note: in definition of macro '__atomicWrite__'
 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \
            ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:86: note: in expansion of macro 'digitalPinToPortReg'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                                                      ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1563:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, LOW);
  ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:85:73: error: 'PORTC' was not declared in this scope
 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))
                                                                         ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:120:12: note: in definition of macro '__atomicWrite__'
 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \
            ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:86: note: in expansion of macro 'digitalPinToPortReg'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                                                      ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1563:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, LOW);
  ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:122:29: error: 'SREG' was not declared in this scope
 uint8_t register saveSreg = SREG;                          \
                             ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:59: note: in expansion of macro '__atomicWrite__'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                           ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1563:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, LOW);
  ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:123:5: error: 'cli' was not declared in this scope
 cli();                                                     \
     ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:59: note: in expansion of macro '__atomicWrite__'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                           ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1563:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, LOW);
  ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:85:28: error: 'PORTD' was not declared in this scope
 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))
                            ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:120:12: note: in definition of macro '__atomicWrite__'
 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \
            ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:86: note: in expansion of macro 'digitalPinToPortReg'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                                                      ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1571:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, HIGH);
  ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:85:64: error: 'PORTB' was not declared in this scope
 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))
                                                                ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:120:12: note: in definition of macro '__atomicWrite__'
 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \
            ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:86: note: in expansion of macro 'digitalPinToPortReg'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                                                      ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1571:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, HIGH);
  ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:85:73: error: 'PORTC' was not declared in this scope
 (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))
                                                                         ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:120:12: note: in definition of macro '__atomicWrite__'
 if ( (int)(A) < 0x40) { bitWrite(*(A), __digitalPinToBit(P), (V) );}  \
            ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:86: note: in expansion of macro 'digitalPinToPortReg'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                                                      ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1571:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, HIGH);
  ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:122:29: error: 'SREG' was not declared in this scope
 uint8_t register saveSreg = SREG;                          \
                             ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:59: note: in expansion of macro '__atomicWrite__'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                           ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1571:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, HIGH);
  ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:123:5: error: 'cli' was not declared in this scope
 cli();                                                     \
     ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/digitalWriteFast.h:132:59: note: in expansion of macro '__atomicWrite__'
 if (__builtin_constant_p(P) && __builtin_constant_p(V))   __atomicWrite__((uint8_t*) digitalPinToPortReg(P),P,V) \
                                                           ^
/Users/pascal/Documents/Arduino/libraries/arduino-dw1000-master/src/DW1000.cpp:1571:2: note: in expansion of macro 'digitalWriteFast'
  digitalWriteFast(_ss, HIGH);
  ^
exit status 1
Error compiling for board Arduino Due (Programming Port).`

Thank you.

### PR DESCRIPTION
**Pull request by Rotzbua**
fixes #84 #40 
digitalWriteFast only supports avr
no need of manual change any more, pre compiler does it

Important note: impact in timing and accuracy on other systems than avr has to be tested and evaluated and may vary highly

### CODE REVIEW

**Comment by Rotzbua** [comment]
change hardware reset like data sheet recommend

**Comment by thotro** [comment]
Great, thanks!

**Comment by MikeS159** [comment]
I have just programmed a tag and anchor with the new PR and I no longer get any ranges (I still get the address and device type over serial port). Has anyone else got this working.

Using 328p on a Uno

**Comment by Rotzbua** [comment]
@MikeS159 Tanks, I will check it, in a view hours. Maybe I forgot some changes from my testing branch. Which ranging or example do you tried?

**Comment by MikeS159** [comment]
It was the DW1000Ranging_Tag/Anchor. I have rolled back to PR #80 which is the last version I can get to work.

**Comment by Rotzbua** [comment]
@MikeS159 I struggle a little bit with a solution. In your roll-back to PR #80 is there my commit cf312e061381bacc134731f05987f508e3402106 with the IRQ pin change included?

**Comment by MikeS159** [comment]
No. I am using pin 2 as IRQ, so my code worked without your change.
If you are trying to use #80 and IRQ is not pin 2 in your hardware you could try changing the hard coded IRQ pin definition (in DW1000.cpp?)

**Pull request merged**
