### PR TITLE
Fix for Cortex M0 (32bit) system

### PR DESCRIPTION
**Pull request by tommag**
This commit solves instability issues during ranging. I still have some problems with the Basic Sender / receiver not working on this platform.

### CODE REVIEW

**Comment by pascalbros** [comment]
Hi, with my arduino due i'm not able to send or receive, can you please explain or show your setup? I'm very interested. Let me know.

Thank you.

**Comment by tommag** [comment]
Hello,

I've had some issues to get it working too, to me the biggest compatibility issue at the moment is the interrupt pin handling. The Arduino code base expects an irq number for AVR platforms and a pin number for other ARM platforms. I just submitted a PR adressing this issue ( #91 ) and I think that now it should work with every user providing the pin number for the IRQ.

With this modification all the examples are working on my HW (Arduino Zero compatible, custom board).

**Comment by tommag** [comment]
@pascalbros Continuing the discussion here as it looks more adapted. Do the ranging examples work for you ? The basic sender / receiver examples didn't work first for an unknown reason, while the ranging examples were OK.

Do you use a hardware reset line ? The software reset didn't seem to work.

These are the problems that I encountered, sorry but can't help you past this point at the moment...

**Comment by pascalbros** [comment]
Hi @tommag thanks for your support.
I did some intensive sessions of debug and the only thing that I noticed is about the SYS_STATUS register.
In my Arduino Pro Mini (it works), the register is 0000800002 before transmitting and 0000000000 after, but for some weird reasons the Due is still 0000800002 after the transmission and also monitoring continuously the SYS_STATUS, it never changes.

I tried to write and read the value back of the address or the PAN, and it works, so my problem is not with the SPI interface or the hardware (tried also to trigger the interrupt manually).

Then I tried to debug the TX message and the setup of the TX registers and are written correctly.

So honestly i don't know why is not sending or receiving, the code is the same and apparently the configuration also.

I tried with the ANCHOR-TAG code, but it uses DW1000Ranging that is based on DW1000 class.
First of all I need to figure out why it doesn't work with DW1000 class, though.

Let me know, Pascal.

**Comment by tommag** [comment]
Sorry but I have no idea... 
I asked about the Anchor / Tag code because it always worked for me whereas the basic sender / receiver was failing (I still don't know why).

Do you have the code that you used to check the SYS_STATUS register ? I could try it on my HW if you want. 

I also encountered a problem with transmissions that were delayed for a very long time (that's the purpose of this PR actually) and seemed not to be processed but were only delayed, could this be the same ?

**Pull request merged**
