### PR TITLE
Use fixed-size integers

### PR DESCRIPTION
**Pull request by Rotzbua**
Hi,
I tried to use the DW1000 with the esp8266.
The esp is a 32bit arm which is different to 8bit atmel (Arduino). So I had to use fixed sized integers (stdint.h) to avoid different behaviour on the different architectures.

Sadly I did not got it stable working on the esp. (seems to be related on the SPI clock generator of the spi). But I want to share my code with you, I tested some functions and it worked so far.

Main changes of PR:
- integers to fixed sized integers
- a lot of todos for the classes and code
- reading of OTP.

Best Rotzbua

### CODE REVIEW

**Comment by aacton** [comment]
@Rotzbua I have the DWM1000 working with the ESP8266. I think your suspicion is correct about the SPI clock. By trial an error, I more-or-less accidentally came across a combination of settings that work pretty reliably. First, I changed _fastSPI to 20 MHz. Then, I had to tweak the code in DW1000::select() because there was something it didn't like about calling enableClock(XTI_CLOCK) before manageLDE(). I wouldn't call my solution production-ready, but I'm happy to share and maybe together we come up with something more stable. What's the best way to share my code? Should I open a pull request?

**Comment by Rotzbua** [comment]
@aacton Hi, I will not work with the esp8266/dw1000 now and in the future. My solution now uses a Sparkfun Pro Micro with 8Mhz@3.3V and I will focus on that combination.
About the SPI speed problem I read something at the elector-magazine (I thing it was the German edition). They programmed a "tuner"-script which runs until the esp8266 has a stable and well known spi speed.

**Comment by thotro** [comment]
Great, many thanks! Cheers!

**Comment by aacton** [comment]
In the interest of closing this loop: Regarding my previous comment about issues with the ESP8266, after much investigation, I traced the issue back to the way the registers were being written when changing clock speed. Using _fastSPI of 20MHz in conjuction with pull request #131 (now merged) fixes the issues.

**Pull request merged**
