### PR TITLE
Fix interrupt number / pin confusion and make it compatible with non-AVR platforms

### PR DESCRIPTION
**Pull request by tommag**

### CODE REVIEW

**Comment by pascalbros** [comment]
Still no luck with my Arduino Due And BasicSender.
My SYS_STATUS is always 0000800002 (CPLOCK SLP2INIT), no bits about TX are set and obviously no interrupt is triggered.

So at this point I don't know, I tried to debug digitalPinToInterrupt with the value "2" and it returns "2".

I have also an Arduino Pro Mini and it works like a charm but I need the Due for some heavy computations and I can't figure out what the hell is going on here.

The setup is the same, the SPI connection works (no error reading or writing) but it simply doesn't send or receive anything.

You have the Zero, it's almost the same of the Due, do you have any suggestions or check list to follow?
Thanks.

**Comment by Rotzbua** [comment]
@tommag great, you found my stupid mistake, with commit cf312e061381bacc134731f05987f508e3402106 I forgot spi.useinterrupt()

This code is not needed, because digitalPinToInterrupt() always translate pin-number -> interrupt-number
```arduino
#ifdef __AVR__
 attachInterrupt(digitalPinToInterrupt(_irq), DW1000Class::handleInterrupt, RISING);
#else
 attachInterrupt(_irq, DW1000Class::handleInterrupt, RISING); //on non-AVR devices (Zero, Due, Teensy, ...), the pin number must be passed to attachInterrupt
#endif
```
should be still
```arduino
 attachInterrupt(digitalPinToInterrupt(_irq), DW1000Class::handleInterrupt, RISING);
```

**Comment by MikeS159** [comment]
@Rotzbua, does this fix the issue in PR [#86](https://github.com/thotro/arduino-dw1000/pull/86)?

**Comment by tommag** [comment]
@Rotzbua You're right, I actually forgot to check the digitalPinToInterrupt definition for non-AVR... 
I modified the PR to include only the SPI part.
Thanks !

**Comment by Rotzbua** [comment]
It should solve all issues. I can not test the DWRanging because I did not get it working on my esp8266, sorry. Basic works.

**Pull request merged**
