### PR TITLE
Implemented antenna calibration API with backwards compatibility

### PR DESCRIPTION
**Pull request by an4cr0n**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Doc update?   | no 
| BC breaks?    | no 
| Deprecations? | no
| Fixed tickets | #... 

This is a simple improvement based on pull request #244 but doesn't break backwards compatibility.

### CODE REVIEW

**Comment by Rotzbua** [comment]
@an4cr0n So #244 is obsolete with this pull request?

**Comment by Sonic0** [comment]
In my opinion, yes. We wait for @an4cr0n

**Comment by an4cr0n** [comment]
@Rotzbua depends if you want to include the python scripts in the other one, but i think they don't belong here.
P.S. Don't merge this as we recently improved the code getting rid of _antennaCalibrated variable.

**Comment by Rotzbua** [comment]
@Sonic0 @an4cr0n thanks for your pull request :+1:  , i merged them before i basically abandon this lib, i hope your code helps others

**Pull request merged**
